
<?php

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_preprocess_page().
 */
function ckeditor_json_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = drupal_get_path('module', 'ckeditor_json') . '/css/ckeditor_json.css';
}

/**
 * Implements hook_preprocess_page().
 */
function ckeditor_json_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'ckeditor_json/ckeditor_json';
}
